[tool.black]
line-length = 100
target-version = ["py310"]
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 100
skip = [".venv", "node_modules", "data"]
known_first_party = ["app", "scripts"]
src_paths = ["app", "scripts"]

[tool.ruff]
line-length = 100
target-version = "py310"
select = ["E", "F", "I", "B", "W", "UP", "C90"]
ignore = ["E203"]
exclude = [
  ".venv",
  "node_modules",
  "data",
]

[tool.ruff.lint.isort]
known-first-party = ["app", "scripts"]

[tool.ruff.format]
quote-style = "preserve"
