name: docker-build

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR (optional)
        if: ${{ secrets.GHCR_TOKEN != '' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deploy/docker/Dockerfile
          platforms: linux/amd64
          push: ${{ secrets.GHCR_TOKEN != '' }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/ollama-rag:latest
            ghcr.io/${{ github.repository_owner }}/ollama-rag:${{ github.ref_name }}
