name: docker-smoke

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deploy/docker/Dockerfile
          platforms: linux/amd64
          push: false
          tags: rag2app:ci

      - name: Run container
        run: |
          docker run -d --rm -p 8000:8000 --name rag2app_ci rag2app:ci
          for i in {1..40}; do
            if curl -fsS http://127.0.0.1:8000 >/dev/null; then echo OK; exit 0; fi
            sleep 0.5
          done
          echo "App did not become healthy in time" >&2
          docker logs rag2app_ci || true
          exit 1

      - name: Cleanup
        if: always()
        run: |
          docker rm -f rag2app_ci 2>/dev/null || true
