name: release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  create_release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release (auto notes)
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
